var cities = [];

// const prepositionParser = require('../preposition');

const modifierParser = require('../modifier');

// function lowercaseFirstLetter(string) {
//     return string.charAt(0).toLowerCase() + string.slice(1);
// }

var prepositions = [ 'to', 'in', 'from', 'into', 'at' ];

module.exports = function (sentence, varName) {
    if (!sentence || typeof sentence !== 'string') {
        return false;
    }

    // console.log(sentence);
    var prep = modifierParser(sentence, prepositions);
    if (prep) {
        sentence = prep.left;
    }
    // console.log(sentence, prep);

    // console.log('capital -city');
    for (var i = 0 ; i < cities.length ; i++) {
        if (sentence.toLowerCase().indexOf(cities[i].toLowerCase()) == 0 ) {
            var left = sentence.slice(cities[i].length);
            var result = {
                left: left,
                vars: {}
            };
            if (varName) {
                result.vars[varName] = {text: cities[i]};
                if (prep) {
                    result.vars[varName].preposition = prep.modifier;
                }
            }
            // console.log(result);
            return result;
        }
    }

    return false;
};

cities = [
'Abu Dhabi',
'Abuja',
'Accra',
'Adamstown',
'Addis Ababa',
'Algiers',
'Alofi',
'Amman',
'Amsterdam',
'Andorra la Vella',
'Ankara',
'Antananarivo',
'Apia',
'Ashgabat',
'Asmara',
'Astana',
'Asuncion',
'Athens',
'Avarua',
'Baghdad',
'Baku',
'Bamako',
'Bandar Seri Begawan',
'Bangkok',
'Bangui',
'Banjul',
'Basseterre',
'Beijing',
'Beirut',
'Belgrade',
'Belmopan',
'Berlin',
'Bern',
'Bishkek',
'Bissau',
'Bogota',
'Brasilia',
'Bratislava',
'Brazzaville',
'Bridgetown',
'Brussels',
'Bucharest',
'Budapest',
'Buenos Aires',
'Bujumbura',
'Cairo',
'Canberra',
'Caracas',
'Castries',
'Cayenne',
'Charlotte Amalie',
'Chisinau',
'Cockburn Town',
'Conakry',
'Copenhagen',
'Dakar',
'Damascus',
'Dhaka',
'Dili',
'Djibouti',
'Dodoma',
'Dar es Salaam',
'Doha',
'Douglas',
'Dublin',
'Dushanbe',
'Edinburgh of the Seven Seas',
'El Aaiun',
'Episkopi Cantonment',
'Flying Fish Cove',
'Freetown',
'Funafuti',
'Gaborone',
'George Town',
'Georgetown',
'Georgetown',
'Gibraltar',
'Grytviken',
'Guatemala City',
'Gustavia',
'Hagutua',
'Hamilton',
'Hanga Roa',
'Hanoi',
'Harare',
'Hargeisa',
'Havana',
'Helsinki',
'Honiara',
'Islamabad',
'Jakarta',
'Jamestown',
'Jerusalem',
'Ramallah',
'Gaza',
'Juba',
'Kabul',
'Kampala',
'Kathmandu',
'Khartoum',
'Kiev',
'Kigali',
'Kingston',
'Kingston',
'Kingstown',
'Kinshasa',
'Kuala Lumpur',
'Putrajaya',
'Kuwait City',
'Libreville',
'Lilongwe',
'Lima',
'Lisbon',
'Ljubljana',
'Lomi',
'London',
'Luanda',
'Lusaka',
'Luxembourg',
'Madrid',
'Majuro',
'Malabo',
'Mali',
'Managua',
'Manama',
'Manila',
'Maputo',
'Marigot',
'Maseru',
'Mata-Utu',
'Mbabane',
'Lobamba',
'Melekeok',
'Ngerulmud',
'Mexico City',
'Minsk',
'Mogadishu',
'Monaco',
'Monrovia',
'Montevideo',
'Moroni',
'Moscow',
'Muscat',
'Nairobi',
'Nassau',
'Naypyidaw',
'N\'Djamena',
'New Delhi',
'Niamey',
'Nicosia',
'Nicosia',
'Nouakchott',
'Noumea',
'Nuku\'alofa',
'Nuuk',
'Oranjestad',
'Oslo',
'Ottawa',
'Ouagadougou',
'Pago Pago',
'Palikir',
'Panama City',
'Papeete',
'Paramaribo',
'Paris',
'Philipsburg',
'Phnom Penh',
'Plymouth',
'Brades Estate',
'Podgorica',
'Cetinje',
'Port Louis',
'Port Moresby',
'Port Vila',
'Port-au-Prince',
'Port of Spain',
'Porto-Novo',
'Cotonou',
'Prague',
'Praia',
'Pretoria',
'Bloemfontein',
'Cape Town',
'Pristina',
'Pyongyang',
'Quito',
'Rabat',
'Reykjavik',
'Riga',
'Riyadh',
'Road Town',
'Rome',
'Roseau',
'Saipan',
'San Jose',
'San Juan',
'San Marino',
'San Salvador',
'Sana\'a',
'Santiag',
'Valparaiso',
'Santo Domingo',
'Sao Tome',
'Sarajevo',
'Seoul',
'Singapore',
'Skopje',
'Sofia',
'Sri Jayawardenepura Kotte',
'Colombo',
'St. George\'s',
'St. Helier',
'St. John\'s',
'St. Peter Port',
'St. Pierre',
'Stanley',
'Stepanakert',
'Stockholm',
'Sucre',
'La Paz',
'Sukhumi',
'Suva',
'Taipei',
'Tallinn',
'Tarawa',
'Tashkent',
'Tbilisi',
'Kutaisi',
'Tegucigalpa',
'Tehran',
'Thimphu',
'Tirana',
'Tiraspol',
'Tokyo',
'Torshavn',
'Tripoli',
'Tskhinvali',
'Tunis',
'Ulan Bator',
'Vaduz',
'Valletta',
'The Valley',
'Vatican City',
'Victoria',
'Vienna',
'Vientiane',
'Vilnius',
'Warsaw',
'Washington D.C.',
'Wellington',
'West Island',
'Willemstad',
'Windhoek',
'Yamoussoukro',
'Abidjan',
'Yaounde',
'Yaren',
'Yerevan',
'Zagreb'
];
